/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.greenrecyclebin.astrology;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ApplicationTest {
}
